// <auto-generated />
using System;
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(sqliteDBContext))]
    [Migration("20260425011631_MigrateToLineupsAgain")]
    partial class MigrateToLineupsAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HiveMind.Server.Entities.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.HasIndex("LineupId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            ChannelName = "Test1",
                            ChannelNumber = 0
                        },
                        new
                        {
                            ChannelId = 2,
                            ChannelName = "Test2",
                            ChannelNumber = 0
                        },
                        new
                        {
                            ChannelId = 3,
                            ChannelName = "Test3",
                            ChannelNumber = 0
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathsToIgnore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Lineup", b =>
                {
                    b.Property<int>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("LineupId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.LineupItem", b =>
                {
                    b.Property<int>("LineupItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LineupItemId");

                    b.HasIndex("LineupId");

                    b.ToTable("LineupItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaItemShowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MediaItemShowId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItemShow", b =>
                {
                    b.Property<int>("MediaItemShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaItemShowTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemShowId");

                    b.ToTable("MediaItemShows");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QueryId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.Property<int>("QueryFilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QueryFilterId");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryFilters");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryLineupItem", b =>
                {
                    b.Property<int>("QueryLineupItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineupItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PadTo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoutType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryType")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueryLineupItemId");

                    b.HasIndex("LineupItemId");

                    b.ToTable("QueryLineupItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Tags", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("MediaItemTags");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Channel", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Lineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId");

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.LineupItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Lineup", "Lineup")
                        .WithMany("LineupItems")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Library", "Library")
                        .WithMany("MediaItems")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.MediaItemShow", "Show")
                        .WithMany()
                        .HasForeignKey("MediaItemShowId");

                    b.Navigation("Library");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Query", "Query")
                        .WithMany("Filters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryLineupItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.LineupItem", null)
                        .WithMany("Queries")
                        .HasForeignKey("LineupItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Lineup", b =>
                {
                    b.Navigation("LineupItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.LineupItem", b =>
                {
                    b.Navigation("Queries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Navigation("Filters");
                });
#pragma warning restore 612, 618
        }
    }
}
