// <auto-generated />
using System;
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(sqliteDBContext))]
    [Migration("20260929124122_ADDBLOCKS")]
    partial class ADDBLOCKS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HiveMind.Server.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Drone", b =>
                {
                    b.Property<int>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationSlots")
                        .HasColumnType("INTEGER");

                    b.HasKey("DroneId");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathsToIgnore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Lineup", b =>
                {
                    b.Property<int>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("LineupId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBlackBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ShowId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategy", b =>
                {
                    b.Property<int>("ProgramStrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvancedDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramStrategyId");

                    b.ToTable("ProgramStrategies");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategyLineup", b =>
                {
                    b.Property<int>("ProgramStrategyLineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgramStrategyLineupId");

                    b.HasIndex("LineupId");

                    b.HasIndex("ProgramStrategyId");

                    b.ToTable("ProgramStrategyLineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryType")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueryId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.Property<int>("QueryFilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QueryFilterId");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryFilters");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.Property<int>("ScheduleBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleBatchId");

                    b.HasIndex("ProgramStrategyId");

                    b.ToTable("ScheduleBatches");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatchItem", b =>
                {
                    b.Property<int>("ScheduleBatchItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyLineUpId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleBatchItemId");

                    b.HasIndex("ScheduleBatchId");

                    b.ToTable("ScheduleBatchItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.SchedulingResult", b =>
                {
                    b.Property<int>("SchedulingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SchedulingResultId");

                    b.ToTable("SchedulingResults");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            SettingsId = 1,
                            Name = "Import_Location",
                            Value = "/"
                        },
                        new
                        {
                            SettingsId = 2,
                            Name = "Export_Location",
                            Value = "/"
                        },
                        new
                        {
                            SettingsId = 3,
                            Name = "Bump In Tag",
                            Value = "In"
                        },
                        new
                        {
                            SettingsId = 4,
                            Name = "Bump Out Tag",
                            Value = "Out"
                        },
                        new
                        {
                            SettingsId = 5,
                            Name = "Bump Generic Tag",
                            Value = "Generic"
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShowId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DroneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationLogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrategyProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StationId");

                    b.HasIndex("DroneId");

                    b.HasIndex("StrategyProgramStrategyId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            StationLogo = "",
                            StationName = "Test1",
                            StationNumber = 1
                        },
                        new
                        {
                            StationId = 2,
                            StationLogo = "",
                            StationName = "Test2",
                            StationNumber = 2
                        },
                        new
                        {
                            StationId = 3,
                            StationLogo = "",
                            StationName = "Test3",
                            StationNumber = 3
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Tags", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplate", b =>
                {
                    b.Property<int>("TransitionTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MatchShowBumps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransitionTemplateId");

                    b.ToTable("TransitionTemplates");

                    b.HasData(
                        new
                        {
                            TransitionTemplateId = 1,
                            MatchShowBumps = true,
                            Name = "Default MidRoll"
                        },
                        new
                        {
                            TransitionTemplateId = 2,
                            MatchShowBumps = true,
                            Name = "Default PostRoll"
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplateSlot", b =>
                {
                    b.Property<int>("TransitionTemplateSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransitionTemplateSlotId");

                    b.HasIndex("TransitionTemplateId");

                    b.ToTable("TransitionTemplateSlots");

                    b.HasData(
                        new
                        {
                            TransitionTemplateSlotId = 1,
                            Slot = 1,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            TransitionTemplateSlotId = 2,
                            Slot = 2,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            TransitionTemplateSlotId = 3,
                            Slot = 4,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            TransitionTemplateSlotId = 4,
                            Slot = 2,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            TransitionTemplateSlotId = 5,
                            Slot = 0,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            TransitionTemplateSlotId = 6,
                            Slot = 2,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            TransitionTemplateSlotId = 7,
                            Slot = 5,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            TransitionTemplateSlotId = 8,
                            Slot = 4,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            TransitionTemplateSlotId = 9,
                            Slot = 2,
                            TransitionTemplateId = 2
                        });
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("MediaItemTags");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Library", "Library")
                        .WithMany("MediaItems")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId");

                    b.Navigation("Library");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategyLineup", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Lineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId");

                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "ProgramStrategy")
                        .WithMany("Lineups")
                        .HasForeignKey("ProgramStrategyId");

                    b.Navigation("Lineup");

                    b.Navigation("ProgramStrategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Query", "Query")
                        .WithMany("Filters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "ProgramStrategy")
                        .WithMany()
                        .HasForeignKey("ProgramStrategyId");

                    b.Navigation("ProgramStrategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatchItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ScheduleBatch", null)
                        .WithMany("ScheduleBatchItems")
                        .HasForeignKey("ScheduleBatchId");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Station", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Drone", null)
                        .WithMany("Stations")
                        .HasForeignKey("DroneId");

                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyProgramStrategyId");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplateSlot", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.TransitionTemplate", null)
                        .WithMany("Slots")
                        .HasForeignKey("TransitionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Drone", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategy", b =>
                {
                    b.Navigation("Lineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.Navigation("ScheduleBatchItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplate", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
