// <auto-generated />
using System;
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(sqliteDBContext))]
    [Migration("20260218030349_MediaItemShowChangeID")]
    partial class MediaItemShowChangeID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HiveMind.Server.Entities.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            ChannelName = "Test1",
                            ChannelNumber = 0
                        },
                        new
                        {
                            ChannelId = 2,
                            ChannelName = "Test2",
                            ChannelNumber = 0
                        },
                        new
                        {
                            ChannelId = 3,
                            ChannelName = "Test3",
                            ChannelNumber = 0
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.CollectionScheduleItem", b =>
                {
                    b.Property<int>("CollectionScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableInterStitials")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableIntroBump")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoutType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionScheduleItemId");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("CollectionScheduleItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryType")
                        .HasColumnType("INTEGER");

                    b.HasKey("LibraryId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemShowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MediaItemShowId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItemShow", b =>
                {
                    b.Property<int>("MediaItemShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaItemShowTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemShowId");

                    b.ToTable("MediaItemShows");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ChannelId = 1,
                            ScheduleName = "Test Schedule",
                            StartTime = new TimeOnly(0, 0, 0)
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleItem", b =>
                {
                    b.Property<int>("ScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleItemId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.CollectionScheduleItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ScheduleItem", null)
                        .WithMany("Collections")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Library", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.MediaItemShow", "Show")
                        .WithMany()
                        .HasForeignKey("MediaItemShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Schedule", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Channel", "Channel")
                        .WithOne("Schedule")
                        .HasForeignKey("HiveMind.Server.Entities.Schedule", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Channel", b =>
                {
                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Schedule", b =>
                {
                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleItem", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
