// <auto-generated />
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(sqliteDBContext))]
    [Migration("20260202174911_AddChannelDummy")]
    partial class AddChannelDummy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HiveMind.Server.Models.Channel", b =>
                {
                    b.Property<int>("ChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelID");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelID = 1,
                            ChannelName = "Test1"
                        },
                        new
                        {
                            ChannelID = 2,
                            ChannelName = "Test2"
                        },
                        new
                        {
                            ChannelID = 3,
                            ChannelName = "Test3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
