// <auto-generated />
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(sqliteDBContext))]
    [Migration("20260203192140_LinkSchedules")]
    partial class LinkSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HiveMind.Server.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            ChannelName = "Test1"
                        },
                        new
                        {
                            ChannelId = 2,
                            ChannelName = "Test2"
                        },
                        new
                        {
                            ChannelId = 3,
                            ChannelName = "Test3"
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("HiveMind.Server.Models.Schedule", b =>
                {
                    b.HasOne("HiveMind.Server.Models.Channel", "Channel")
                        .WithOne("Schedule")
                        .HasForeignKey("HiveMind.Server.Models.Schedule", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("HiveMind.Server.Models.Channel", b =>
                {
                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
