// <auto-generated />
using System;
using HiveMind.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiveMind.Server.Migrations
{
    [DbContext(typeof(SqliteDBContext))]
    partial class sqliteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HiveMind.Server.Entities.Drone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationSlots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathsToIgnore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Lineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBlackBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ShowId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromoDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStrategyId");

                    b.HasIndex("QueryId");

                    b.ToTable("ProgramEvents");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvancedDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgramStrategies");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategyLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineupId");

                    b.HasIndex("ProgramStrategyId");

                    b.ToTable("ProgramStrategyLineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("QueryFilters");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStrategyId");

                    b.ToTable("ScheduleBatches");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyLineupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleBatchId");

                    b.ToTable("ScheduleBatchItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.SchedulingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgramStrategyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchedulingResults");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Import_Location",
                            Value = "/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Export_Location",
                            Value = "/"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bump In Tag",
                            Value = "In"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bump Out Tag",
                            Value = "Out"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bump Generic Tag",
                            Value = "Generic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Schedule Retention Days",
                            Value = "7"
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DroneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DroneId");

                    b.HasIndex("StrategyId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "",
                            Name = "Test1",
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Logo = "",
                            Name = "Test2",
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Logo = "",
                            Name = "Test3",
                            Number = 3
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MatchShowBumps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransitionTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchShowBumps = true,
                            Name = "Default MidRoll"
                        },
                        new
                        {
                            Id = 2,
                            MatchShowBumps = true,
                            Name = "Default PostRoll"
                        });
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplateSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransitionTemplateId");

                    b.ToTable("TransitionTemplateSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Index = 0,
                            Slot = 1,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Index = 1,
                            Slot = 2,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Index = 2,
                            Slot = 4,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Index = 3,
                            Slot = 2,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Index = 4,
                            Slot = 0,
                            TransitionTemplateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Index = 0,
                            Slot = 2,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            Id = 7,
                            Index = 1,
                            Slot = 5,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            Id = 8,
                            Index = 2,
                            Slot = 4,
                            TransitionTemplateId = 2
                        },
                        new
                        {
                            Id = 9,
                            Index = 3,
                            Slot = 2,
                            TransitionTemplateId = 2
                        });
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MediaItemTags");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.MediaItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Library", "Library")
                        .WithMany("MediaItems")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId");

                    b.Navigation("Library");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramEvent", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "ProgramStrategy")
                        .WithMany()
                        .HasForeignKey("ProgramStrategyId");

                    b.HasOne("HiveMind.Server.Entities.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStrategy");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategyLineup", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Lineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId");

                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "ProgramStrategy")
                        .WithMany("Lineups")
                        .HasForeignKey("ProgramStrategyId");

                    b.Navigation("Lineup");

                    b.Navigation("ProgramStrategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.QueryFilters", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Query", "Query")
                        .WithMany("Filters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "ProgramStrategy")
                        .WithMany()
                        .HasForeignKey("ProgramStrategyId");

                    b.Navigation("ProgramStrategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatchItem", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.ScheduleBatch", null)
                        .WithMany("ScheduleBatchItems")
                        .HasForeignKey("ScheduleBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Station", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.Drone", null)
                        .WithMany("Stations")
                        .HasForeignKey("DroneId");

                    b.HasOne("HiveMind.Server.Entities.ProgramStrategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplateSlot", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.TransitionTemplate", null)
                        .WithMany("Slots")
                        .HasForeignKey("TransitionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaItemTags", b =>
                {
                    b.HasOne("HiveMind.Server.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiveMind.Server.Entities.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Drone", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Library", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ProgramStrategy", b =>
                {
                    b.Navigation("Lineups");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.Query", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.ScheduleBatch", b =>
                {
                    b.Navigation("ScheduleBatchItems");
                });

            modelBuilder.Entity("HiveMind.Server.Entities.TransitionTemplate", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
